DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
	P_ID VARCHAR2(20) PRIMARY KEY,
	P_NAME VARCHAR2(20) NOT NULL,
	PRICE NUMBER NOT NULL,
	DES VARCHAR2(20)
);

INSERT INTO PRODUCT
VALUES('LT_SS7','»ï¼º ³ëÆ®ºÏ',1570000, '°¶·Â½ÃºÏ ÀÌ¿Â');

INSERT INTO PRODUCT
VALUES('LT_AMP16','¸ÆºÏÇÁ·Î',3900000, 'MackbookPro 16');
INSERT INTO PRODUCT
VALUES('PC_IBM','IBMPC',750000, 'WINDOWS8');

SELECT * FROM PRODUCT WHERE P_ID ='LTSS7'